"""
This is a build_macos.py script generated by py2applet

Usage:
    python build_macos.py py2app
"""

from setuptools import setup

APP = ['.\\src\\ytdwnld.py']
DATA_FILES = []
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
