name: ytdwnld build and release develop

on:
  push:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

        pip install -r requirements.txt

    - name: Add short hash to version file
      run: |
        DEV_VERSION=$(python git_version.py)

        # add without new line
        echo -n $DEV_VERSION >> ytdwnld_version    

        FULL_VERSION=$(cat ytdwnld_version) >> $GITHUB_ENV   

    - name: Build windows
      run: |
        python .\build_windows.py py2exe

    - name: Publish windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/ytdwnld.exe
        asset_name: ytdwnld ${{ env.FULL_VERSION }}.exe
        asset_content_type: application/octet-stream



